### ISSUE TITLE
add safer version of hasOwnProperty()

### ISSUE THREAD

**Issue by davepacheco** [davepacheco/node-jsprim#14]
It's common to use `obj.hasOwnProperty(key)` to determine if the object `obj` has a property called `key`.  This fails badly if `obj` can have a key called `hasOwnProperty` that's unrelated to the method.  This might be possible of `obj` is an object whose keys represent HTTP headers sent by an untrusted user.  Such a user can break a program using `obj.hasOwnProperty(key)` by passing a header called `hasOwnProperty`.  To avoid this, programs can use `Object.hasOwnProperty.call(obj, key)`.  This is a little obscure (and verbose), so it would be nice to have a jsprim method to implement this.

**Comment by jclulow** [comment]
Can it be a relatively short method, e.g. `hasProp(obj, x)` ?

**Comment by davepacheco** [comment]
Sure.  I'm not necessarily planning to do this right away.  I filed an issue so I wouldn't forget about it.

**Comment by davepacheco** [comment]
This was done a while ago.
