### ISSUE TITLE
add hrtime addition and conversion routines

### ISSUE THREAD

**Issue by jclulow** [davepacheco/node-jsprim#6]
It would be good to have a more complete suite of routines to add/accumulate `process.hrtime()` readings, as well as convert them to scalar time units for display and aggregation.  For example:

* `hrtimeAdd(a, b)` -- add two hrtime readings (`a` and `b`) together and return the result as a new array
* `hrtimeAccum(a, b)` -- add reading `b` to reading `a` and store the result in `a`
* `hrtimeNanosec(a)` -- convert the hrtime reading `a` into a scalar number of nanoseconds
* `hrtimeMicrosec(a)` -- convert the hrtime reading `a` into a scalar number of microseconds
* `hrtimeMillisec(a)` -- convert the hrtime reading `a` into a scalar number of milliseconds

While we're at it, we should rename `hrtimediff()` to `hrtimeDiff()` (but leaving an alias for compatibility with existing code).

**Comment by davepacheco** [comment]
LGTM.

**Comment by jclulow** [comment]
Thanks.  Now released in `jsprim@1.1.0`.
